openapi: 3.0.3
info:
  title: Workspace Data Service
  version: 0.1.0
  description: Workspace Data Service API
  termsOfService: https://github.com/DataBiosphere/terra-workspace-data-service
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
paths:
  /{instanceid}/entities/{v}/{type}/{id}:
    get:
      summary: Get entity
      description: Get entity
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/entityIdPathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Entity'
    put:
      summary: Create entity
      description: Create entity
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/entityIdPathParam'
      responses:
        201:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Entity'
    patch:
      summary: Update entity
      description: Update entity
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/entityIdPathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Entity'
    delete:
      summary: Delete entity
      description: Delete entity
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/entityIdPathParam'
      responses:
        204:
          description: Success
  /{instanceid}/types/{v}/{type}:
    patch:
      summary: Update entity type
      description: |
        Update entity type. Alpha1 supports renaming a type; future versions will support modifying schema details
        such as changing the attribute schema for this type.
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EntityTypeDefinition'
    delete:
      summary: Delete entity type
      description: Delete entity type. This deletes all entities of this type.
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
      responses:
        204:
          description: Success
  /{instanceid}/types/{type}/attributes/{v}/{attribute}:
    patch:
      summary: Update attribute
      description: |
        Update attribute. Alpha1 supports renaming an attribute within the specified type;
        future versions will support modifying schema details
        such as changing the datatype of this attribute.
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/attributePathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EntityTypeDefinition'
    delete:
      summary: Delete attribute
      description: |
        Delete attribute. This deletes all values for this attribute within the specified type.
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
        - $ref: '#/components/parameters/entityTypePathParam'
        - $ref: '#/components/parameters/attributePathParam'
      responses:
        204:
          description: Success
  /{instanceid}/search/{v}:
    get:
      summary: Query entities
      description: Paginated list of entities matching the criteria supplied in url query parameters
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EntityQueryResponse'
    post:
      summary: Query entities
      description: Paginated list of entities matching the criteria supplied in the request body
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/EntityQueryResponse'
  /{instanceid}/batch/{v}:
    post:
      summary: Batch write entities
      description: Perform a batch of create / delete / update operations on multiple entities
      parameters:
        - $ref: '#/components/parameters/instanceIdPathParam'
        - $ref: '#/components/parameters/versionPathParam'
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BatchResponse'
components:
  parameters:
    attributePathParam:
      name: attribute
      in: path
      description: Attribute name
      required: true
      schema:
        type: string
    entityIdPathParam:
      name: id
      in: path
      description: Entity id
      required: true
      schema:
        type: string
    entityTypePathParam:
      name: type
      in: path
      description: Entity type
      required: true
      schema:
        type: string
    instanceIdPathParam:
      name: instanceid
      in: path
      description: WDS instance id
      required: true
      schema:
        type: string
    versionPathParam:
      name: v
      in: path
      description: API version
      required: true
      schema:
        type: string
        default: alpha1
  schemas:
    BatchResponse:
      type: object
    Entity:
      required:
        - id
        - type
        - metadata
        - attributes
      type: object
      properties:
        id:
          type: string
          description: Entity id
        type:
          type: string
          description: Entity type
        attributes:
          $ref: '#/components/schemas/EntityAttributes'
          description: KVPs of entity attributes
        metadata:
          $ref: '#/components/schemas/EntityMetadata'
          description: Provenance and other entity metadata. May not be present in alpha1.
    EntityAttributes:
      type: object
    EntityAttributeDefinition:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          description: Attribute name
    EntityMetadata:
      type: object
    EntityQueryResponse:
      type: object
    EntityTypeDefinition:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          description: Entity type name

