version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    labels:
      - "dependencies"
      - "gradle"
    open-pull-requests-limit: 10
    reviewers:
      - "@DataBiosphere/analysisjourneys"
    commit-message:
      prefix: "[AJ-1782]"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    groups:
      minor-and-patch-updates:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    reviewers:
      - "@DataBiosphere/analysisjourneys"
    commit-message:
      prefix: "[AJ-1782]"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
