version: 2
registries:
  broad-artifactory:
    type: maven-repository
    url: https://broadinstitute.jfrog.io/artifactory/libs-release
updates:
  - package-ecosystem: "gradle"
    registries:
      - "broad-artifactory"
    ignore:
      - dependency-name: "bio.terra:datarepo-client"
      - dependency-name: "bio.terra:workspace-manager-client"
      - dependency-name: "org.broadinstitute.dsde.workbench:leonardo-client_*"
      - dependency-name: "org.broadinstitute.dsde.workbench:sam-client_*"
    directory: "/"
    labels:
      - "dependencies"
      - "gradle"
    open-pull-requests-limit: 10
    reviewers:
      - "@DataBiosphere/broad-core-services"
    commit-message:
      prefix: "[CORE-70]"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    groups:
      minor-and-patch-updates:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    reviewers:
      - "@DataBiosphere/broad-core-services"
    commit-message:
      prefix: "[CORE-70]"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    groups:
      artifact-actions:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
