#!/bin/sh

# Based on: https://medium.com/@mmessell/apply-spotless-formatting-with-git-pre-commit-hook-1c484ea68c34
# Note: running git add in pre-commit is not recommended, which is why this pre-commit hook isn't enabled
# by default.
stagedFiles=$(git diff --staged --name-only)

echo "Running spotlessApply. Formatting code..."
./gradlew spotlessApply

for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done
