# coding: utf-8

# flake8: noqa

"""
    Workspace Data Service

    This page lists both current and proposed APIs. The proposed APIs which have not yet been implemented are marked as deprecated. This is incongruous, but by using the deprecated flag, we can force swagger-ui to display those endpoints differently.  Error codes and responses for proposed APIs are likely to change as we gain more clarity on their implementation.  As of v0.2, all APIs are subject to change without notice.   # noqa: E501

    The version of the OpenAPI document: v0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.instances_api import InstancesApi
from openapi_client.api.records_api import RecordsApi
from openapi_client.api.schema_api import SchemaApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.attribute_schema import AttributeSchema
from openapi_client.models.batch_operation import BatchOperation
from openapi_client.models.batch_record_request import BatchRecordRequest
from openapi_client.models.batch_response import BatchResponse
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.record_attribute_definition import RecordAttributeDefinition
from openapi_client.models.record_query_response import RecordQueryResponse
from openapi_client.models.record_request import RecordRequest
from openapi_client.models.record_response import RecordResponse
from openapi_client.models.record_type_schema import RecordTypeSchema
from openapi_client.models.request_body_search import RequestBodySearch
from openapi_client.models.search_operator import SearchOperator
from openapi_client.models.search_request import SearchRequest
from openapi_client.models.search_sort_direction import SearchSortDirection
from openapi_client.models.stack_trace_element import StackTraceElement

