samurl: https://sam.dsde-prod.broadinstitute.org/

rawlsUrl: https://rawls.dsde-prod.broadinstitute.org/
drshubUrl: https://drshub.dsde-prod.broadinstitute.org/

twds:
  data-import:
    allowed-hosts:
      - service\.prod\.anvil\.gi\.ucsc\.edu
      - .*\.singlecell\.gi\.ucsc\.edu,
      - .*gen3\.biodatacatalyst\.nhlbi\.nih\.gov
      - .*service\.azul\.data\.humancellatlas\.org
      - .*redcaptest\.vumc\.org
      - .*redcap\.vumc\.org
    sources:
      - urls:
          - ^https:\/\/.*gen3\.biodatacatalyst\.nhlbi\.nih\.gov\/
          - ^https:\/\/gen3-biodatacatalyst-nhlbi-nih-gov-pfb-export\.s3\.amazonaws\.com\/
          - ^https:\/\/s3\.amazonaws.com\/gen3-biodatacatalyst-nhlbi-nih-gov-pfb-export\/
          - ^https:\/\/pic-sure-auth-prod-data-export\.s3\.amazonaws\.com\/
          - ^https:\/\/s3\.amazonaws\.com\/pic-sure-auth-prod-data-export\/
          - ^https:\/\/s3\.amazonaws\.com\/edu-ucsc-gi-platform-anvil-prod-storage-anvilprod\.us-east-1\/
          - ^https:\/\/nih-nhlbi-.*\.amazonaws\.com\/
          # anvil data is in TDR now, these are the old URLs
          - ^https:\/\/gen3-theanvil-io-pfb-export\.s3\.amazonaws\.com\/
          - ^https:\/\/s3\.amazonaws\.com\/gen3-theanvil-io-pfb-export\/
        requirePrivateWorkspace: true
        requireProtectedDataPolicy: true
        requiredAuthDomainGroups:
          - "federal_data_lockdown"

# Set the allowed hosts for drs pfb imports
drs:
  allowed-hosts:
    - repo-prod\.prod\.sagebase\.org
