samurl: https://sam.dsde-prod.broadinstitute.org/

rawlsUrl: https://rawls.dsde-prod.broadinstitute.org/
drshubUrl: https://drshub.dsde-prod.broadinstitute.org/

twds:
  data-import:
    allowed-hosts:
      - service\.prod\.anvil\.gi\.ucsc\.edu
      - .*\.singlecell\.gi\.ucsc\.edu,
      - .*gen3\.biodatacatalyst\.nhlbi\.nih\.gov
      - .*service\.azul\.data\.humancellatlas\.org
      - .*redcaptest\.vumc\.org
      - .*redcap\.vumc\.org

# Set the allowed hosts for drs pfb imports
drs:
  allowed-hosts:
    - repo-prod\.prod\.sagebase\.org
