samurl: https://sam.dsde-prod.broadinstitute.org/
datarepourl: https://data.terra.bio/
workspacemanagerurl: https://workspace.dsde-prod.broadinstitute.org/
leoUrl: https://leonardo.dsde-prod.broadinstitute.org/
