# These values are used more than once, so we'll set them here with appropriate defaults
env:
  wds:
    db:
      host: ${WDS_DB_HOST:localhost}
      port: ${WDS_DB_PORT:5432}
      name: ${WDS_DB_NAME:wds}
      password: ${WDS_DB_PASSWORD:wds}
      user: ${WDS_DB_USER:wds}
      # When running on Azure in k8s with workload identity set ADDITIONAL_JDBC_URL_PARAMS to
      # sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin
      additionalUrlParams: ${ADDITIONAL_JDBC_URL_PARAMS:prepareThreshold=0}

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState,db
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "info,health,prometheus"
      base-path: /
      path-mapping:
        info: version
        health: status
        prometheus: prometheus
  # additional keys to expose in the actuator info endpoint:
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

  # Note: this will probably get re-nested under `prometheus` if prometheus-rsocket-proxy is upgraded to support
  # spring-boot 3+
  metrics.export.prometheus.rsocket:
    # TODO(AJ-1342): disabled by default, enable once prod readiness is approved
    enabled: ${PROMETHEUS_RSOCKET_PROXY_ENABLED:false}
    host: ${PROMETHEUS_RSOCKET_PROXY_HOST:}
    port: 7001
    max-retries: 1000 # default is Long.MAX_VALUE
    first-backoff: 10s
    max-backoff: 10m

info:
  app:
    chart-version: ${HELM_CHART:unknown}
    image: ${WDS_IMAGE:unknown}

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

  cloud:
    gcp:
      storage:
        enabled: false
    #TODO arrange this in the right files and hierarchy
      pubsub:
        project-id: terra-importservice-dev
        topic: import-service-notify-local
#      credentials:
#        location: file:/Users/bmorgan/dev/workbench/terra-workspace-data-service/terra-importservice-dev-20bc15025667.json


  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${env.wds.db.host}:${env.wds.db.port}/${env.wds.db.name}?reWriteBatchedInserts=true&${env.wds.db.additionalUrlParams}
      username: ${env.wds.db.user}
      password: ${env.wds.db.password}
      maximum-pool-size: 7
      minimum-idle: 7
  mvc:
    problemdetails:
      # TODO AJ-1157: can we turn this back on?
      enabled: false
  servlet:
    multipart.max-request-size: 5GB
    multipart.max-file-size: 5GB
  sql:
    init:
      # Disable having spring-boot from automatically creating the schema for the embedded datasource
      mode: never
  # ... and run Liquibase instead
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
  quartz:
    # Quartz will persist all its information in memory. This is simple and performant and
    # allows Quartz to use sensitive data such as auth tokens as input to jobs. However,
    # it is not restart-safe; if WDS restarts or dies before a Quartz job completes, that
    # job will be lost and appear to the end user as if it hung.
    # It is also not cluster-aware; when WDS runs as a multi-replica cluster, Quartz jobs will
    # always run on the replica where they were created.
    job-store-type: memory

#   # activate the "local" profile to turn on CORS response headers,
#   # which may be necessary for local development.
#   profiles:
#     active: local

# set hikari logging to DEBUG or even TRACE to troubleshoot connection pool issues
logging:
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO

server:
  error:
    include-stacktrace: never
    include-message: always

twds:
  write.batch.size: 5000
  streaming.fetch.size: 5000
  instance:
    # Workspace Id for launching instance
    workspace-id: ${WORKSPACE_ID:}
    source-workspace-id: ${SOURCE_WORKSPACE_ID:}
  # short-lived credentials to use during cloning
  startup-token: ${STARTUP_TOKEN:}
  # tenancy & data-import defaults match data-plane, but the source of truth for these configs
  # should be application-data-plane.yml or application-control-plane.yml; they are provided here
  # to allow Spring to boot without crashing and allow StartupConfig to run and check preconditions
  tenancy:
    allow-virtual-collections: false
    require-env-workspace: true
  data-import:
    batch-write-record-sink: "wds"

  pg_dump:
    path: ${PGDUMP_PATH:/usr/bin/pg_dump}
    psqlPath: ${PSQL_PATH:/usr/bin/psql}
    port: ${env.wds.db.port}
    user: ${env.wds.db.user}
    dbName: ${env.wds.db.name}
    password: ${env.wds.db.password}
    host: ${env.wds.db.host}
    # When running on Azure in k8s with workload identity set PGDUMP_USE_AZURE_IDENTITY to true
    useAzureIdentity: ${PGDUMP_USE_AZURE_IDENTITY:true}

sentry:
  dsn: https://e59ecdd940784bd2922f25a0f3197ffd@o54426.ingest.sentry.io/4504299946835968
  mrg: ${LZ_MRG:}
  releasename: ${RELEASE_NAME:}

# retry configuration for REST clients (Sam, WSM, TDR, Leo, etc)
rest:
  retry:
    maxAttempts: 5
    backoff:
      delay: 500
      multiplier: 1.5

# retry configuration for WDS APIs
api:
  retry:
    maxAttempts: 10
    backoff:
      delay: 150
      multiplier: 1.5

samurl: ${SAM_URL:}
datarepourl: ${DATA_REPO_URL:}
workspacemanagerurl: ${WORKSPACE_MANAGER_URL:}
leoUrl: ${LEONARDO_URL:}
