samurl: https://sam.dsde-alpha.broadinstitute.org/
datarepourl: https://data.alpha.broadinstitute.org/
workspacemanagerurl: https://workspace.dsde-alpha.broadinstitute.org/
leoUrl: https://leonardo.dsde-alpha.broadinstitute.org/
