samurl: https://sam.dsde-staging.broadinstitute.org/
datarepourl: https://data.staging.envs-terra.bio/
workspacemanagerurl: https://workspace.dsde-staging.broadinstitute.org/
leoUrl: https://leonardo.dsde-staging.broadinstitute.org/
rawlsUrl: https://rawls.dsde-staging.broadinstitute.org/
