samurl: ${SAM_URL:https://sam.dsde-dev.broadinstitute.org/}
workspacemanagerurl: ${WORKSPACE_MANAGER_URL:https://workspace.dsde-dev.broadinstitute.org/}
leoUrl: ${LEONARDO_URL:https://leonardo.dsde-dev.broadinstitute.org/}
rawlsUrl: ${RAWLS_URL:https://rawls.dsde-dev.broadinstitute.org/}
drshuburl: ${DRS_HUB_URL:https://drshub.dsde-dev.broadinstitute.org/}

twds:
  instance:
    # Workspace Id for launching instance
    workspace-id: ${WORKSPACE_ID:123e4567-e89b-12d3-a456-426614174000}

# enable color-coding for logs
spring:
  output:
    ansi:
      enabled: always

# use the MDC "requestId" as the log correlation pattern. If/when we use Micrometer tracing to
# create correlation ids, this should be removed.
logging:
  pattern:
    correlation: "%X{requestId} "

