# Note: this will probably get re-nested under `prometheus` if prometheus-rsocket-proxy is upgraded to support
# spring-boot 3+
#
# To run a local prometheus-rsocket-proxy (see https://github.com/micrometer-metrics/prometheus-rsocket-proxy):
#    docker run -p 8081:8080 -p 7001:7001 micrometermetrics/prometheus-rsocket-proxy:latest
#
# To run WDS with this profile enabled:
#    ./gradlew bootRun --args='--spring.profiles.active=local-promprox'
management.metrics.export.prometheus.rsocket:
  enabled: true
  host: localhost
