samurl: https://sam.dsde-staging.broadinstitute.org/
datarepourl: https://data.staging.broadinstitute.org/
workspacemanagerurl: https://workspace.dsde-staging.broadinstitute.org/
leoUrl: https://leonardo.dsde-staging.broadinstitute.org/
