samurl: ${SAM_URL:https://sam.dsde-dev.broadinstitute.org/}
datarepourl: https://jade.datarepo-dev.broadinstitute.org/
workspacemanagerurl: ${WORKSPACE_MANAGER_URL:https://workspace.dsde-dev.broadinstitute.org/}
leoUrl: https://leonardo.dsde-dev.broadinstitute.org/

twds:
  instance:
    # Workspace Id for launching instance
    workspace-id: ${WORKSPACE_ID:123e4567-e89b-12d3-a456-426614174000}

# enable color-coding for logs
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gcp:
      pubsub:
        #TODO presumably developer will not have permissions here; what should we use?
        # Using the import-service project and topic, will be updated to cWDS' own at a later date
        project-id: import-service-dev
        topic: import-service-notify-dev
# use the MDC "requestId" as the log correlation pattern. If/when we use Micrometer tracing to
# create correlation ids, this should be removed.
logging:
  pattern:
    correlation: "%X{requestId} "
