samurl: https://sam.dsde-staging.broadinstitute.org/

rawlsUrl: https://rawls.dsde-staging.broadinstitute.org/
drshubUrl: https://drshub.dsde-staging.broadinstitute.org/

# Set the allowed hosts for drs pfb imports
drs:
  allowed-hosts:
    - jade\.datarepo-.*\.broadinstitute\.org
  sources:
    - urls:
        - ^https:\/\/storage\.googleapis\.com\/datarepo-.*-snapshot-export-bucket
        - ^https:\/\/storage\.googleapis\.com\/fixtures-for-tests
      requirePrivateWorkspace: false
      requireProtectedDataPolicy: false
      requiredAuthDomainGroups:
