samurl: https://sam.dsde-prod.broadinstitute.org/
datarepourl: https://data.terra.bio/
workspacemanagerurl: https://workspace.dsde-prod.broadinstitute.org/
leoUrl: https://leonardo.dsde-prod.broadinstitute.org/

spring:
  cloud:
    gcp:
      pubsub:
        # Using the import-service project and topic, will be updated to cWDS' own at a later date
        project-id: import-service-prod
        topic: import-service-notify-prod
