name: 'create bee'
description: 'Creates a bee for the wds e2e test'
inputs:
  token:
    description: 'The auth token to use for bee creation'
    required: true
    type: string
  bee_name:
    description: 'The name of the bee to create'
    required: true
    type: string
  project_name:
    description: 'The name of billing project'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: dispatch to terra-github-workflows
      uses: broadinstitute/workflow-dispatch@v3
      with:
        workflow: attach-billing-project-to-landing-zone.yaml
        repo: broadinstitute/terra-github-workflows
        ref: refs/heads/main
        token: '${{ inputs.token }}'
        inputs: >-
          {
          "bee-name": "${{ inputs.bee_name }}",
          "billing-project": "${{ inputs.project_name }}",
          "service-account": "firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com"
          }
