openapi: 3.0.3

info:
  title: cWDS API Spec
  version: v0.2
  description: |
    Welcome to cWDS.
  termsOfService: https://github.com/DataBiosphere/terra-workspace-data-service
  license:
    name: BSD
    url: https://opensource.org/licenses/BSD-3-Clause

servers:
  - url: /

tags:
  # Tags should be listed in the order they should appear in the UI
  - name: Import
    description: Import APIs
  - name: Job
    description: Job APIs
  - name: General WDS Information
    description: Information regarding versioning, health, info, etc. for WDS
  - name: Capabilities
    description: Describes the features of WDS

paths:
  # Paths should be grouped by their tag, following the order of tags listed above.
  # Within each tag group, paths should be listed alphabetically.

  ##############################
  # Import APIs
  ##############################
  /{instanceUuid}/import/v1:
    # OpenApi requires "/" to be replaced with "~1" in the path being referenced
    $ref: 'apis-v1.yaml#/paths/~1{instanceUuid}~1import~1v1'

  ##############################
  # Job APIs
  ##############################
  /job/v1/{jobId}:
    $ref: 'apis-v1.yaml#/paths/~1job~1v1~1{jobId}'
  /job/v1/instance/{instanceUuid}:
    $ref: 'apis-v1.yaml#/paths/~1job~1v1~1instance~1{instanceUuid}'

  ##############################
  # General WDS Information APIs
  ##############################
  /status:
    $ref: 'openapi-docs.yaml#/paths/~1status'
  /version:
    $ref: 'openapi-docs.yaml#/paths/~1version'

  ##############################
  # Capabilities APIs
  ##############################
  /capabilities/v1:
    # OpenApi requires "/" to be replaced with "~1" in the path being referenced
    $ref: 'apis-v1.yaml#/paths/~1capabilities~1v1'

