openapi: 3.0.3

info:
  title: cWDS API Spec
  version: v1
  description: |
    cWDS - the (c)ontrol-plane (W)orkspace (D)ata (S)ervice - is responsible for importing
    tabular data into the Data tab of a workspace.
  termsOfService: https://github.com/DataBiosphere/terra-workspace-data-service
  license:
    name: BSD
    url: https://opensource.org/licenses/BSD-3-Clause

security:
  - bearerAuth: [ ]

tags:
  # Tags should be listed in the order they should appear in the UI
  - name: Import
    description: Import APIs
  - name: Job
    description: Job APIs
  - name: Workspace
    description: Workspace APIs
  - name: General WDS Information
    description: Information regarding versioning, health, info, etc. for WDS

paths:
  # Paths should be grouped by their tag, following the order of tags listed above.
  # Within each tag group, paths should be listed alphabetically.


  # OpenApi requires "/" to be replaced with "~1" when referencing paths in another file.

  ##############################
  # Import APIs
  ##############################
  /{instanceUuid}/import/v1:
    $ref: 'apis-v1.yaml#/paths/~1{instanceUuid}~1import~1v1'

  ##############################
  # Job APIs
  ##############################
  /job/v1/{jobId}:
    $ref: 'apis-v1.yaml#/paths/~1job~1v1~1{jobId}'
  /job/v1/instance/{instanceUuid}:
    $ref: 'apis-v1.yaml#/paths/~1job~1v1~1instance~1{instanceUuid}'

  ##############################
  # Workspace APIs
  ##############################
  /workspaces/v1/{workspaceId}:
    $ref: 'apis-v1.yaml#/paths/~1workspaces~1v1~1{workspaceId}'

  ##############################
  # General WDS Information APIs
  ##############################
  /status:
    $ref: 'openapi-docs.yaml#/paths/~1status'
  /version:
    $ref: 'openapi-docs.yaml#/paths/~1version'

components:
  # within each group, components should be listed alphabetically.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
