name: 'create bee'
description: 'Creates a bee for the wds e2e test'
inputs:
  token:
    description: 'The auth token to use for bee creation'
    required: true
    type: string
  bee_name:
    description: 'The name of the bee to create'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: dispatch to terra-github-workflows
      uses: broadinstitute/workflow-dispatch@v3
      with:
        workflow: bee-create
        repo: broadinstitute/terra-github-workflows
        ref: refs/heads/main
        token: '${{ inputs.token }}'
        inputs: >-
          { 
          "bee-name": "${{ inputs.bee_name }}", 
          "bee-template-name": "rawls-e2e-azure-tests", 
          "version-template": "dev" 
          }
