package org.databiosphere.workspacedataservice.dao;

import java.util.UUID;
import org.databiosphere.workspacedataservice.shared.model.WdsCollection;
import org.springframework.data.repository.CrudRepository;

/** Spring Data repository for managing WdsCollection objects in the sys_wds.collection table */
public interface CollectionRepository extends CrudRepository<WdsCollection, UUID> {

  // the following methods will automatically be generated by Spring Data:

  /*
  <S extends WdsCollection> S save(S entity);
  <S extends WdsCollection> Iterable<S> saveAll(Iterable<S> entities);
  Optional<WdsCollection> findById(UUID uuid);
  boolean existsById(UUID uuid);
  Iterable<WdsCollection> findAll();
  Iterable<WdsCollection> findAllById(Iterable<UUID> uuids);
  long count();
  void deleteById(UUID uuid);
  void delete(WdsCollection entity);
  void deleteAllById(Iterable<? extends UUID> uuids);
  void deleteAll(Iterable<? extends WdsCollection> entities);
  void deleteAll();
  */
}
