# The App Context includes the following information derived from GitHub Context:
#
# - App Version:
#     - Version tag recorded in Git / version file when code is integrated into mainline.
# - App Branch:
#     - Name of the branch that runs this workflow.
# - App SHA:
#     - Git hash recorded in history.
#     - For PRs: This is the commit hash of the PR changes when the PR is opened, updated with merge commit, or updated with rebase.
#     - For Push: This is the commit hash that results from merging the PR changes into the base (mainline) branch.
# - App Short SHA:
#     - First 7 characters of App SHA.
# - PART:
#     - The part of the version which was bumped.
#
# After successfully running this action, the following environment variables are available for use in subsequent steps within the same job:
#
# - APP_VERSION
# - APP_BRANCH
# - APP_SHA
# - APP_SHORT_SHA
# - PART
#
# Additionally, the step will output the following variables for use in subsequent steps or jobs:
#
# - app_version
# - app_branch
# - app_sha
# - app_short_sha
# - part
#
name: Determine App Context
description: 'Determine the app context from artifacts or version file based on the GitHub Context (PR or mainline merge).'
inputs:
  gh_repo:
    description: 'GitHub repository being used: owner/repository'
    required: true
  max_retries:
    description: 'Maximum number of retries'
    required: false
    default: '15'
  sleep_time:
    description: 'Sleep time between retries in seconds'
    required: false
    default: '5'
outputs:
  app_version:
    description: 'The context-dependent app version'
    value: ${{ steps.app-context.outputs.APP_VERSION }}
  app_branch:
    description: 'The context-dependent app branch'
    value: ${{ steps.app-context.outputs.APP_BRANCH }}
  app_sha:
    description: 'The context-dependent app sha'
    value: ${{ steps.app-context.outputs.APP_SHA}}
  app_short_sha:
    description: 'The context-dependent app sha (short version)'
    value: ${{ steps.app-context.outputs.APP_SHORT_SHA}}
  part:
    description: 'The semver bump mode used for calculating the app version: major, minor, patch'
    value: ${{ steps.app-context.outputs.PART}}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        token: ${{ env.GITHUB_TOKEN }}

    - id: app-context
      name: App Context
      run: ./scripts/ci-hooks/get-app-context.sh
      shell: bash
      env:
        GITHUB_REPO: ${{ inputs.gh_repo }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        MAX_RETRIES: ${{ inputs.max_retries }}
        SLEEP_TIME: ${{ inputs.sleep_time }}
