name: Perf Benchmarks

on:
#  push:
#    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ '**' ]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  benchmark:
    name: Relative performance benchmarking
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Initialize Postgres DB
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql

      - name: Mock Sam via command-line docker run
        run: |
          docker run -v ${{ github.workspace }}/service/src/test/resources/nginx.conf:/etc/nginx/nginx.conf:ro -p 9889:80 -d nginx:1.23.3

      # Run benchmark via JMH gradle plugin https://github.com/melix/jmh-gradle-plugin
      - name: Run benchmark
        run: |
          SAM_URL=http://localhost:9889 ./gradlew jmh

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      # Run `github-action-benchmark` action
      - name: Add benchmark PR job summary
        uses: benchmark-action/github-action-benchmark@v1.16.2
        with:
          # What benchmark tool the output.txt came from
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: service/build/reports/jmh/results.json

          # Where the previous data file is stored
          # external-data-json-path: ./cache/benchmark-data.json

          # GitHub API token to make a commit comment or job summary
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable Job Summary for PRs
          summary-always: true
          comment-always: true
          #
          alert-threshold: "200%"
          # Workflow will fail when an alert happens
          fail-on-alert: false
          # Enable alert commit comment
          comment-on-alert: true
          # Mention @davidangb in the commit comment
          # alert-comment-cc-users: '@davidangb'
          # Disable github pages
          auto-push: true
          gh-pages-branch: gh-pages # this is the default

          # benchmark graphs available at https://databiosphere.github.io/terra-workspace-data-service/dev/bench/
          benchmark-data-dir-path: docs/dev/bench

          save-data-file: true
