name: POC Mock Sam

on:
  pull_request:
    branches: [ '**' ]

jobs:
  poc-mock-sam:
    name: Proof of concept of a mock Sam
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize Postgres DB
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql

      - name: Mock Sam via command-line docker run
        run: |
          docker run -v ${{ github.workspace }}/mock-sam/nginx.conf:/etc/nginx/nginx.conf:ro -p 9889:80 -d nginx:1.23.3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run WDS service and tests
        # the curl statements below will cause failures in WDS if WDS can't talk to Sam.
        # by specifying SAM_URL here, we're pointing WDS at the mock Sam we started above via nginx
        # see mock-sam/nginx.conf for nginx config: the mock always returns 200 with a response body of "true"
        # for any requests to /api/resources/*
        run: |
          export SAM_URL=http://localhost:9882
          ./gradlew bootRun &
          sleep 30
          curl -v -X POST http://localhost:8080/instances/v0.2/123e4567-e89b-12d3-a456-426614174000
          curl -v -X DELETE http://localhost:8080/instances/v0.2/123e4567-e89b-12d3-a456-426614174000
