name: Publish contract tests
on:
  pull_request:
    branches:
      - main
    paths-ignore: [ '**.md' ]
    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
    # types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths-ignore: [ '**.md' ]

env:
  WDS_RUN_ID: ${{ github.event.repository.name }}-${{ github.run_id }}
  PUBLISH_CONTRACT_RUN_NAME: 'publish-contracts-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}'
  WDS_PACTS_ARTIFACT: wds-pacts-${{ github.event.repository.name }}-${{ github.run_id }}
  WDS_PACTS_OUTPUT_DIR: service/build/pacts/
  CAN_I_DEPLOY_RUN_NAME: 'can-i-deploy-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}'

jobs:
  # The app-context job retrieves the App Context artifact that was uploaded
  # through the compute-app-context.yml workflow. If the last commit was
  # a version file bump, this workflow is skipped. Additionally, this workflow
  # runs when a PR targeting mainline is opened, updated (with merge commit or rebase),
  # or when there is a push to the mainline branch.
  app-context:
    if: "!startsWith(github.event.head_commit.message, 'bump ')"
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get-app-context.outputs.app_version }}
      app_branch: ${{ steps.get-app-context.outputs.app_branch }}
      app_sha: ${{ steps.get-app-context.outputs.app_sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Action Type
        run: |
          echo "Action Type: ${{ github.event.action }}"

      - name: Determine App Context
        id: get-app-context
        uses: ./.github/actions/get-app-context
        with:
          gh_repo: ${{ github.repository }}
          max_retries: 20
          sleep_time: 3
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}

      - name: App Context Properties
        run: |
          echo "APP_VERSION=${{ env.APP_VERSION }}"
          echo "APP_BRANCH=${{ env.APP_BRANCH }}"
          echo "APP_SHA=${{ env.APP_SHA }}"
          echo "APP_SHORT_SHA=${{ env.APP_SHORT_SHA }}"
          echo "app_version=${{ steps.get-app-context.outputs.app_version }}"
          echo "app_branch=${{ steps.get-app-context.outputs.app_branch }}"
          echo "app_sha=${{ steps.get-app-context.outputs.app_sha }}"
          echo "app_short_sha=${{ steps.get-app-context.outputs.app_short_sha }}"

  run-consumer-contract-tests:
    runs-on: ubuntu-latest
    needs: [ app-context ]
    outputs:
      pact-paths: ${{ steps.locate-pacts.outputs.pact-paths }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.app-context.outputs.app_sha }}
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run consumer tests
        run: ./gradlew pactTests

      - name: Locate pact files
        id: locate-pacts
        run: |
          pactPaths=$(find "$WDS_PACTS_OUTPUT_DIR" -type f -name "*.json" | jq -cnR "[inputs]")
          echo "pact-paths=$pactPaths" >> $GITHUB_OUTPUT

      - name: Upload pact files to artifact
        id: upload-pacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WDS_PACTS_ARTIFACT }}
          path: ${{ env.WDS_PACTS_OUTPUT_DIR }}
          retention-days: 1

  publish-pacts-job:
    runs-on: ubuntu-latest
    needs: [ app-context, run-consumer-contract-tests ]
    strategy:
      matrix:
        pact_path: ${{ fromJson(needs.run-consumer-contract-tests.outputs.pact-paths) }}
    steps:
      - name: App Context Summary
        run: |
          echo "App Branch: ${{ needs.app-context.outputs.app_branch }}"
          echo "App Version: ${{ needs.app-context.outputs.app_version }}"

      - name: Download pact files from artifact
        id: download-pacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WDS_PACTS_ARTIFACT }}
          path: ${{ env.WDS_PACTS_OUTPUT_DIR }}

      - name: Encode pact as non-breaking base64 string
        id: encode-pact
        run: |
          nonBreakingB64=$(cat "${{ matrix.pact_path }}" | base64 -w 0)
          echo "pact-b64=${nonBreakingB64}" >> $GITHUB_OUTPUT

      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4
        with:
          run-name: '${{ env.PUBLISH_CONTRACT_RUN_NAME }}-${{ matrix.pact_path }}'
          workflow: .github/workflows/publish-contracts.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN }} # github token for access to kick off a job in the private repo
          inputs: '{
            "run-name": "${{ env.PUBLISH_CONTRACT_RUN_NAME }}-${{ matrix.pact_path }}",
            "pact-b64": "${{ steps.encode-pact.outputs.pact-b64 }}",
            "repo-owner": "${{ github.repository_owner }}",
            "repo-name": "${{ github.event.repository.name }}",
            "repo-branch": "${{ needs.app-context.outputs.app_branch }}",
            "release-tag": "${{ needs.app-context.outputs.app_version }}"
          }'

  can-i-deploy: # The can-i-deploy job will run as a result of a PR. It reports the pact verification statuses on all deployed environments.
    runs-on: ubuntu-latest
    needs: [ app-context, publish-pacts-job ]
    strategy:
      matrix:
        pacticipant-name: ["wds", "cwds"]
    steps:
      - name: Dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v4
        with:
          run-name: "${{ env.CAN_I_DEPLOY_RUN_NAME }}-${{ matrix.pacticipant-name }}"
          workflow: .github/workflows/can-i-deploy.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN }} # github token for access to kick off a job in the private repo
          inputs: '{
            "run-name": "${{ env.CAN_I_DEPLOY_RUN_NAME }}-${{ matrix.pacticipant-name }}",
            "pacticipant": "${{ matrix.pacticipant-name }}",
            "version": "${{ needs.app-context.outputs.app_version }}"
          }'
