name: Publish
on: 
  create:
      tags:
        - '*'
  push:
    branches:
      - aj-628-python-client

jobs:
  publish-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
        
      - name: Build all projects without running tests
        run: ./gradlew --build-cache build -x test

      - name: Publish API client to Artifactory
        run: ./gradlew --build-cache :client:artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: libs-snapshot-local
  python-client-job:
      uses: DataBiosphere/terra-workspace-data-service/.github/workflows/release-python-client.yaml@main
