name: Notify via slack

on:
  push:
    branches:
      - aj-945-terra-helm
      
jobs:
  build:
    name: Dependency Submission
    runs-on: ubuntu-latest

    steps:
        - name: "Notify AJ Slack about push on main"
          # see https://github.com/broadinstitute/action-slack
          uses: broadinstitute/action-slack@v3.8.0
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          with:
            status: ${{ job.status }}
            channel: "#dsp-analysis-journeys-alerts"
            username: "terra-workspace-data-service-git"
            author_name: "wds-github"
            icon_emoji: ":triangular_ruler:"
            fields: job, commit
