name: Gradle Dependency Submission
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Dependency Submission
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
