name: Gradle Dependency Submission
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Dependency Submission
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Submit Dependencies
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-project-path: "terra-workspace-data-service"
          gradle-build-module: |-
            :service
            :client
            
