name: Tag
on:
  push:
    branches:
      - dh-aj-719

jobs:
  tag-job:
    runs-on: ubuntu-latest
    outputs:
          new_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_TOKEN }} # this allows the push to succeed later
          
      - name: Bump the tag to a new version
        # https://github.com/DataBiosphere/github-actions/tree/master/actions/bumper
        uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          VERSION_FILE_PATH: build.gradle
          VERSION_LINE_MATCH: "^\\s*version\\s*=\\s*'.*'"
          VERSION_SUFFIX: SNAPSHOT
  python-client-job:
      needs: tag-job
      uses: ./.github/workflows/release-python-client.yml
      with:
        new-tag: ${{ needs.tag-job.outputs.new_tag }}
      secrets:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  java-client-job:
      uses: ./.github/workflows/publish-java-client.yml
      secrets:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  docker-image-job:
      needs: tag-job
      uses: ./.github/workflows/publish-docker.yml
      with:
        new-tag: ${{ needs.tag-job.outputs.new_tag }}
      secrets:
        ACR_SP_PASSWORD: ${{ secrets.ACR_SP_PASSWORD }}
        ACR_SP_USER: ${{ secrets.ACR_SP_USER }}
        BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}

