name: Tag
on:
  push:
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ '**' ]
#  push:
#    branches:
#    - main

jobs:
  tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Bump versions in WDS VERSION.txt file
        env:
          VERSION_FILE_PATH: build.gradle
          VERSION_LINE_MATCH: "^\\s*version\\s*=\\s*'.*'"
        run: |
          set -e
          pwd
          ls
          env

#      - name: Bump the tag to a new version
#        # https://github.com/DataBiosphere/github-actions/tree/master/actions/bumper
#        uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
#        id: tag
#        env:
#          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
#          DEFAULT_BUMP: patch
#          RELEASE_BRANCHES: main
#          VERSION_FILE_PATH: build.gradle
#          VERSION_LINE_MATCH: "^\\s*version\\s*=\\s*'.*'"
#          VERSION_SUFFIX: SNAPSHOT

