name: token-testing
'on':
  push:
    branches:
      - aj-1287-test
env:
  BEE_NAME: aj1287temptesting
  TOKEN: '${{ secrets.BROADBOT_TOKEN }}'
  RUN_NAME_SUFFIX: >-
    ${{ github.event.repository.name }}-${{ github.run_id }}-${{
    github.run_attempt }}
jobs:
  create-bee-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v3
        with:
          workflow: bee-create
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: '${{ env.TOKEN }}'
          inputs: '{ "bee-name": "${{ env.BEE_NAME }}", "version-template": "dev" }'
  attach-landing-zone-to-bee-workflow:
    runs-on: ubuntu-latest
    needs:
      - create-bee-workflow
    steps:
      - name: dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v3
        with:
          workflow: attach-landing-zone-to-bee.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/iv-az-e2e-1
          token: '${{ env.TOKEN }}'
          inputs: >-
            { "run-name": "attach-landing-zone-to-bee-${{ env.RUN_NAME_SUFFIX
            }}", "bee-name": "${{ env.BEE_NAME }}", "billing-project":
            "tmp-billing-project-aj1287", "billing-project-creator":
            "hermione.owner@quality.firecloud.org", "service-account":
            "firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com" }
  run-e2e-test-job:
    runs-on: ubuntu-latest
    needs:
      - create-bee-workflow
      - attach-landing-zone-to-bee-workflow
    steps:
      - name: Generate OAuth2 2.0 access token for billing project creator
        id: owner_auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: >-
            projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider
          service_account: 'firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com'
          access_token_scopes: 'profile, email, openid'
          access_token_subject: 'hermione.owner@quality.firecloud.org'
          export_environment_variables: false
      - name: Set environment variables
        run: |
          echo "AZURE_TOKEN=${{ steps.owner_auth.outputs.access_token }}" >> $GITHUB_ENV
          echo "BEE_NAME=${{ env.BEE_NAME }}" >> $GITHUB_ENV
          echo "BILLING_PROJECT_NAME=tmp-billing-project-aj1287" >> $GITHUB_ENV
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run test
        run: |
          pytest e2e-test/e2etest.py
  delete-billing-project-v2-from-bee-workflow:
    runs-on: ubuntu-latest
    needs:
      - create-bee-workflow
      - attach-landing-zone-to-bee-workflow
    if: false
    steps:
      - name: dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v3
        with:
          workflow: .github/workflows/delete-billing-project-v2-from-bee.yaml
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/iv-az-e2e-1
          token: '${{ env.TOKEN }}'
          inputs: >-
            { "run-name": "delete-billing-project-v2-from-bee-${{
            env.RUN_NAME_SUFFIX }}", "bee-name": "${{ env.BEE_NAME }}",
            "billing-project": "tmp-billing-project-aj1287",
            "billing-project-creator": "hermione.owner@quality.firecloud.org",
            "service-account":
            "firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com" }
  destroy-bee-workflow:
    runs-on: ubuntu-latest
    needs:
      - delete-billing-project-v2-from-bee-workflow
    if: false
    steps:
      - name: dispatch to terra-github-workflows
        uses: broadinstitute/workflow-dispatch@v3
        with:
          workflow: bee-destroy
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: '${{ env.TOKEN }}'
          inputs: '{ "bee-name": "${{ env.BEE_NAME }}" }'
