name: Test Python client

on:
  push:
    branches:
      - aj-816-pc-tests
  pull_request:
    paths:
      - '**/openapi-docs.yaml'

jobs:
  build-n-test:
    name: Build and test WDS Python client
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Use Node.js ${{matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install openapi-generator-cli
        run: npm install @openapitools/openapi-generator-cli -g

      - name: set version to 4.3.1
        run: openapi-generator-cli version-manager set 4.3.1

      - name: Generate Python client
        run: |
          openapi-generator-cli generate \
          -i service/src/main/resources/static/swagger/openapi-docs.yaml \
          -g python \
          -o wds-client \
          --additional-properties=projectName=wds-client,packageName=wds_client,packageVersion=1.0.0 \
          --skip-validate-spec

      - name: Install python package locally
        working-directory: ./wds-client
        run: |
          pip install .

      - name: Initialize Postgres DB
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run WDS service and tests
        run: |
            export WORKSPACE_ID=c9ed46a9-fc9b-4130-a608-cf3760ed70a0
            ./gradlew --build-cache build -x test
            ./gradlew bootRun &
            count=20
            until $(curl --output /dev/null --silent --head --fail http://localhost:8080/status); do
              printf '.'
              sleep 1
              count=$(expr $count - 1) 
              if [ "$count" -eq "0" ]; then
                echo "WDS is not responding, exit action."
                exit
              fi
            done
            pip install pytest
            pytest service/src/test/python/test.py
